
`timescale 1ns / 1ps

//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 22.04.2024 01:12:51
// Design Name: Blowfish Testbench
// Module Name: tb_blowfish
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// This test bench monitors the subkeys generated by the blowfish_key_expansion module.
// 
// Dependencies:
// blowfish_key_expansion.v
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1ps

module blowfish_testbench;

  // Input key for encryption and decryption (32 bits)
  reg [31:0] key;

  // Plaintext data to be encrypted (64 bits)
  reg [63:0] plaintext;

  // Encrypted output from the blowfish_encrypt module (64 bits)
  wire [63:0] ciphertext;

  // Decrypted output from the blowfish_decrypt module (64 bits)
  wire [63:0] decryptedtext;

  // Instantiate the blowfish_encrypt module
  blowfish_encrypt encrypt_inst (
    .key(key),
    .plaintext(plaintext),
    .ciphertext(ciphertext)
  );

  // Instantiate the blowfish_decrypt module
  blowfish_decrypt decrypt_inst (
    .key(key),
    .dec_ciphertext(ciphertext),
    .decryptedtext(decryptedtext)
  );

  // Initialization block for test data and simulation control
  initial begin
    // Set a simple key value
    key = 32'h10101010;

    // Set a sample plaintext value
    plaintext = 64'h0123401234012340;

    // Display the initial key and plaintext values
    $display("key:%h", key);
    $display("plaintext:%h", plaintext);

    // Introduce a delay of 10 time units and then finish the simulation
    #10 $finish;
  end

endmodule




